### ISSUE TITLE
staros是基于onos的控制器吗？本地部署是否需要onos环境？

### ISSUE THREAD

**Issue by leoching** [starosxyz/staroscontroller#1]

**Comment by wfnex** [comment]
不需要onos环境。
staros界面是用了onos界面。 接口我们尽量兼容onos.  staros的应用编程采用xml+javascript。 所以开发者门槛很低。 底层是采用c++做驱动引擎。封装了openflow/netconf等协议。性能要比onos高。
onos目前的缺点是各个厂商向里面添加了很多别人用不到的功能。导致onos非常庞大，无用代码很多。


我们的staros控制器就很精简。


谢谢你的关注。
 
 
------------------ Original ------------------

**Comment by leoching** [comment]
closed
